CC=nvc
CXX=nvc++
CFLAGS=-mp=gpu
SRCS = $(wildcard *.c)
PROGS = $(patsubst %.c,%.out,$(SRCS))

all: $(PROGS)

%.out: %.c
	$(CC) $(CFLAGS)  -o $@ $<

clean-src: clean
	$(RM) $(SRCS)

clean:
	$(RM) $(PROGS)
